### ISSUE TITLE
Use global_cache_dir to download

### ISSUE THREAD

**Issue by SlothOfAnarchy** [stuvusIT/wordpress#10]

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 416 days.

**Comment by Scriptkiddi** [comment]
what cache dir? local on your machine or on the server

**Comment by SlothOfAnarchy** [comment]
local on your machine so that the server does not need Internet access

**Comment by Scriptkiddi** [comment]
this is irrelevant since wp_cli does not use your pc
